Fix usage of mutable strings for OCaml >4.02
There were lots of errors and warnings about this:

    + /usr/bin/ocamlc.opt -c -g -I ../lem-ocaml-lib-for-cmm/_build/ -g -I cil-parser -o pp.cmo pp.ml
    File "pp.ml", line 1181, characters 12-25:
    1181 |     let r = String.create l in
                       ^^^^^^^^^^^^^
    Alert deprecated: Stdlib.String.create
    Use Bytes.create/BytesLabels.create instead.
    File "pp.ml", line 1182, characters 26-43:
    1182 |     for i = 0 to l - 1 do String.unsafe_set r i (f(String.unsafe_get s i)) done;
                                     ^^^^^^^^^^^^^^^^^
    Alert deprecated: Stdlib.String.unsafe_set
    File "pp.ml", line 1183, characters 4-5:
    1183 |     r
               ^
    Error: This expression has type bytes but an expression was expected of type
             string

Similar in other files. The reason is that since OCaml 4.02, strings are
no longer mutable. So for all mutations, we switch to a sequence of
bytes instead, and convert back to a string at the end.